spring:
  application:
    name: user-api
  datasource:
    url: jdbc:postgresql://localhost:5432/db_radcare
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Brazil/East
server:
  port: ${PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetchRegistry: true
    registerWithEureka: true

